################################################################################
#
# Copyright (C) 2020 BadPixxel <www.badpixxel.com>
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
################################################################################

################################################################
# Defined Pipeline Stages
stages:
  - docker
  - tests
  - deploy

################################################################
# Functional Tests
################################################################

.core_tests:    &core_tests
    stage:      tests
    tags:       [ Dedicated ]
    script:
        # Composer Build
        - cat ci/composer.sh | sh
        # Execute Grump Travis Testsuite
        - cat ci/grumphp.sh | sh
    after_script:
        # Run After Script
        - cat ci/after.sh | sh

tests:php-8.1:
    image: registry.gitlab.com/badpixxel-projects/php-sdk:php-8.1
    <<: *core_tests

tests:php-8.0:
    image: registry.gitlab.com/badpixxel-projects/php-sdk:php-8.0
    <<: *core_tests

tests:php-7.4:
    image: registry.gitlab.com/badpixxel-projects/php-sdk:php-7.4
    <<: *core_tests

################################################################
# Build Docker Images for Testing
################################################################
.docker:        &docker
  stage:        docker
  image:        docker:stable
  tags:         [ Dedicated-Docker ]
  services:
    - docker:dind
  variables:
    IMAGE_TAG: "$CI_REGISTRY_IMAGE:$CI_JOB_NAME"
  before_script:
    - docker info
  script:
    - echo "[$CI_JOB_NAME] Build & Upload Docker Image"
    ################################################################
    # Connect Docker to GitLab
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    ################################################################
    # Build & Upload Splash All Docker Images
    - docker build -t $IMAGE_TAG docker/$CI_JOB_NAME
    - docker push $IMAGE_TAG
    ################################################################
    # Connect Docker to DockerHub
    - docker login -u splashsync -p $DOCKER_HUB_TOKEN
    ################################################################
    # Build & Upload Splash All Docker Hub Images
    - docker build -t splashsync/php-sdk:$CI_JOB_NAME docker/$CI_JOB_NAME
    - docker push splashsync/php-sdk:$CI_JOB_NAME

  except:
    - schedules
  only:
    changes:
      - docker/**/*
      - .gitlab-ci.yml

php-7.2:
  <<: *docker

php-7.3:
    <<: *docker

php-7.4:
    <<: *docker

php-8.0:
    <<: *docker

php-8.1:
    <<: *docker

jekyll:
    <<: *docker

jekyll-7.4:
    allow_failure:  true
    <<: *docker

#################################################################
## Build Documentation
#################################################################
pages:
    image:      registry.gitlab.com/badpixxel-projects/php-sdk:jekyll
    stage:      deploy
    retry:      2
    tags:       [ Dedicated ]
    ################################################################################
    # Run Test Script
    script:
        # Run Composer to Build Dependencies
        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/composer.sh  | bash
        # Build Documentation
        - php vendor/bin/grumphp run --tasks=build-docs
    artifacts:
        paths:
            - public
