################################################################################
#
# Copyright (C) 2020 BadPixxel <www.badpixxel.com>
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
################################################################################

################################################################
# Defined Pipeline Stages
stages:
  - docker
  - tests

################################################################
# Build Docker Images for Testing
################################################################
docker:
  stage:      docker
  image:      docker:stable
  tags:
    - docker
  services:
    - docker:dind
  before_script:
    - docker info
  script:
    # Connect Docker to GitLab
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    # Build & Upload Splash All Docker Images
    - bash docker/update.sh
  except:
    - schedules
  only:
    changes:
      - docker/*

################################################################
# Functional Tests
################################################################

.core_tests:    &core_tests
    image: registry.gitlab.com/badpixxel/php-sdk:php-7.3
    stage:      docker
    tags:
        - Dedicated
    script:
        # Composer Build
        - cat  travis/composer.sh | sh
        # Execute Grump Travis Testsuite
        - cat travis/grumphp.sh | sh
    after_script:
        # Run After Script
        - cat  travis/after.sh | sh

#tests:php-7.4:
#  image: registry.gitlab.com/badpixxel/php-sdk:php-7.3
#  <<: *core_tests

tests:php-7.4:
  image: registry.gitlab.com/badpixxel/php-sdk:php-7.4
  <<: *core_tests

tests:php-7.3:
  image: registry.gitlab.com/badpixxel/php-sdk:php-7.3
  <<: *core_tests

tests:php-7.2:
  image: registry.gitlab.com/badpixxel/php-sdk:php-7.2
  <<: *core_tests

