#############################################
#   Config for Files Lint Tasks
#############################################

grumphp:
    tasks:
        phplint:
            exclude:                "%exclude%"
        jsonlint:
            detect_key_conflicts:   true
            ignore_patterns:        "%exclude%"
        xmllint:
            ignore_patterns:        "%exclude%"
        yamllint:
            parse_custom_tags:      true
            ignore_patterns:        "%exclude%"
        twigcs:
            path:                   '.'
            severity:               'warning'
            ruleset:                'FriendsOfTwig\Twigcs\Ruleset\Official'
            triggered_by:           ['twig']
            exclude:                "%exclude%"
        git_blacklist:
            keywords:
                - "var_dump"
                - "dump("
                - "console.log"
                - "print_r"
                - "die("
            triggered_by:           ['php', 'js', 'twig']