#############################################
#   Config for Php Cut & Paste Detector
#############################################
grumphp:
    tasks:
        phpcpd:
            triggered_by:     ['php']
            exclude:          "%exclude%"