#############################################
#   Config for Core Analyze Tasks
#############################################
grumphp:
    tasks:
        #############################################
        #   Composer Verifications
        composer: ~
        #############################################
        #   Symfony Security Checks
        securitychecker: ~